version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: ember-cli
    versions:
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: release-it
    versions:
    - 14.5.0
    - 14.5.1
    - 14.6.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-source
    versions:
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.3
  - dependency-name: highlight.js
    versions:
    - 9.18.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
